task1 is success!
task2 is fail!
[ERROR] package.Exception : message
at 1
task3 is success!